class RandomError(Exception):
    pass
def complete_the_process():
    raise RandomError("Some Random error")
